name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-default-config --no-color -qo '011'"
          annotate: warning

      - name: Create Retail Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g retail -m .pkgmeta.yml
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Create Classic Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g cata -m .pkgmeta-classic.yml
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Create Classic Era Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic -m .pkgmeta-classic.yml
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
